//lcd.h
//MMI enumerated Screen Numbers

enum Screens
{
	TBT_MMI_SCREEN, 
	TBT_MMI_WELCOME_SCREEN,
	TBT_MMI_TEST_CONFIGURATION,  		
	TBT_RELAY_SELECTION,			        
	TBT_MMI_RECORD_INFO,					
	TBT_MMI_NEW_SETTINGS,				
	TBT_MMI_MAIN_MENU_KEYS,				
	TBT_MMI_TEST_SELECTION,				
	TBT_MMI_RELAY_SETTING,				
	TBT_MMI_DATE_TIME_SETTINGS,			
	TBT_MMI_BATTERY_NUMERIC_KEY,			
	TBT_MMI_NEW_RELAY_KEY1,				
	TBT_MMI_NEW_RELAY_KEY1_K2,			
	TBT_MMI_NEW_RELAY_KEY1_K3,			
	TBT_MMI_NEW_RELAY_KEY1_PR,			
	TBT_MMI_IGNITE_KEY,					
	TBT_MMI_RELAY_SELECTION_KEYS,		
	TBT_MMI_CONNECT_BATTERY,				
	TBT_MMI_TEST_COMPLETED,				
	TBT_MMI_TEST_PROCESSING,				
	TBT_MMI_RESET_ABORT,					
	TBT_MMI_CONNECT_LOAD,				
	SETTINGS,							
	TBT_MMI_TEST_STATUS ,
	TBT_MMI_CONDITION_MENU,	
	TBT_MMI_CONDITION_50_1,
	TBT_MMI_CONDITION_50_2,
	TBT_MMI_CONDITION_50_3,
	TBT_MMI_CONDITION_50_4,
	TBT_MMI_CONDITION_50_5,	
	TBT_MMI_SECTION_SETTINGS,
	TBT_MMI_SECTION1_SETTINGS,
	TBT_MMI_SECTION2_SETTINGS
};

